apiVersion: v1
kind: Pod
metadata:
  name: alma-linux
  namespace: expense
  labels:
    app: web
    tier: frontend
spec:
  containers:
    - name: almalinux
      image: chandrahari296/frontend:v3.0.0