apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  namespace: expense
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /tmp/myvolume/
  ####
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - main
                
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: expense
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: expense
spec:
  containers:
    - name: nginx
      image: chandrahari296/frontend:v2.0.0
      ports:
        - containerPort: 81
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginx-volume
  volumes:
    - name: nginx-volume
      persistentVolumeClaim:
        claimName: nginx-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: expense-service
  namespace: expense
spec:
  ports:
    - port: 8080 # kubernetes internal communication port (ingress)
      protocol: TCP
      targetPort: 81  # app port
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  generation: 2
  name: expense-app-ingress
  namespace: expense
spec:
  ingressClassName: public
  rules:
    - host: expense.durgasri.com
      http:
        paths:
          - backend:
              service:
                name: expense-service
                port:
                  number: 8080
            path: /
            pathType: Prefix