apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name.app }}-deployment
  labels:
    app: {{ .Values.name.app }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.name.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.name.app }}
    spec:
      containers:
        - name: {{ .Values.name.app }}
          image: chandrahari296/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
