apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: expense
  labels:
    app.kubernetes.io/name: nginx
spec:
  containers:
    - name: nginx
      image: chandrahari296/frontend:v2.0.0
      ports:
        - containerPort: 81
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginx-volume
  volumes:
    - name: nginx-volume
      persistentVolumeClaim:
        claimName: nginx-pvc